package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/bufbuild/protocompile/experimental/protoscope"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/encoding/prototext"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/dynamicpb"
)

const BASIC_JSON = `{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "name": "Hiro Protagonist",
  "email": "hiro@metaverse.com",
  "age": 24,
  "heightCm": 175.5,
  "weightKg": 70.2,
  "role": "ROLE_ADMIN",
  "birthDate": { "year": 1992, "month": 5, "day": 22 }
}`

func main() {
	// 1. Get FileDescriptorSet using buf
	// We run this from the root of the project
	cmd := exec.Command("buf", "build", "..", "-o", "-#format=bin")
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "buf build failed: %v\n%s\n", err, stderr.String())
		os.Exit(1)
	}

	fdsBytes := stdout.Bytes()
	fds := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(fdsBytes, fds); err != nil {
		fmt.Fprintf(os.Stderr, "failed to unmarshal FDS: %v\n", err)
		os.Exit(1)
	}

	// 2. Create registry
	files, err := protodesc.NewFiles(fds)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to create registry: %v\n", err)
		os.Exit(1)
	}

	desc, err := files.FindDescriptorByName("demo.v1.User")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to find User descriptor: %v\n", err)
		os.Exit(1)
	}
	messageDesc := desc.(protoreflect.MessageDescriptor)

	// 3. Create message from JSON
	msg := dynamicpb.NewMessage(messageDesc)
	if err := protojson.Unmarshal([]byte(BASIC_JSON), msg); err != nil {
		fmt.Fprintf(os.Stderr, "failed to unmarshal JSON: %v\n", err)
		os.Exit(1)
	}

	// 4. Generate formats

	// IDL (read from file)
	idlBytes, _ := os.ReadFile("../proto/demo/v1/user.proto")
	idl := string(idlBytes)

	// Binary (Hex) - Use Deterministic to ensure stable field order
	binBytes, _ := proto.MarshalOptions{Deterministic: true}.Marshal(msg)

	// Stability Round-trip:
	// Unmarshaling from deterministic binary into a fresh message 
	// helps ensure that subsequent text/json marshaling follows 
	// a consistent field-number order.
	stableMsg := dynamicpb.NewMessage(messageDesc)
	_ = proto.Unmarshal(binBytes, stableMsg)

	hexStr := ""
	for i, b := range binBytes {
		if i > 0 {
			hexStr += " "
		}
		hexStr += fmt.Sprintf("%02x", b)
	}

	// ProtoJSON
	jsonBytes, _ := protojson.MarshalOptions{
		Multiline: true,
		Indent:    "  ",
	}.Marshal(stableMsg)

	// ProtoText
	textBytes, _ := prototext.MarshalOptions{
		Multiline: true,
		Indent:    "  ",
	}.Marshal(stableMsg)

	// Protoscope (using experimental/protoscope library)
	scopeStr, err := protoscope.Disassemble(binBytes, protoscope.DisassembleOptions{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "protoscope disassemble failed: %v\n", err)
		os.Exit(1)
	}

	// FDS JSON (human readable for the UI)
	// We only show the demo/v1/user.proto file to keep the UI responsive
	displayFds := &descriptorpb.FileDescriptorSet{}
	for _, f := range fds.File {
		if f.GetName() == "demo/v1/user.proto" {
			f.SourceCodeInfo = nil
			displayFds.File = append(displayFds.File, f)
		}
	}
	// Stabilize FDS as well
	fdsBin, _ := proto.MarshalOptions{Deterministic: true}.Marshal(displayFds)
	stableFds := &descriptorpb.FileDescriptorSet{}
	_ = proto.Unmarshal(fdsBin, stableFds)
	fdsJson, _ := protojson.MarshalOptions{Multiline: true, Indent: "  "}.Marshal(stableFds)

	// 5. Output TS
	fmt.Println("// AUTO-GENERATED by examples-gen/main.go")
	fmt.Println("// DO NOT EDIT MANUALLY")
	fmt.Println("")
	fmt.Println("export const STATIC_FACES = {")
	fmt.Printf("  idl: `%s`,\n", strings.TrimSpace(idl))
	fmt.Printf("  fds: `%s`,\n", strings.TrimSpace(string(fdsJson)))
	fmt.Printf("  bin: \"%s\",\n", hexStr)
	fmt.Printf("  json: `%s`,\n", strings.TrimSpace(string(jsonBytes)))
	fmt.Printf("  txt: `%s`,\n", strings.TrimSpace(string(textBytes)))
	fmt.Printf("  scope: `%s`\n", strings.TrimSpace(scopeStr))
	fmt.Println("};")
}
