name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install: true
      - name: Install dependencies
        run: pnpm web-install
      - name: Lint
        run: just web-check
